name: Build h3cuda wheel

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv wheel
          pipenv install --dev --deploy

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev


      - id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.7
        with:
          cuda: '11.7.0'

      - name: Echo Version
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

      - name: Echo Version
        run: |
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - name: Echo Version
        run: |
          nvcc -V

      - name: Build Wheel
        working-directory: h3cuda_pkg/
        run: |
          make wheel

      - name: Archive whl result
        uses: actions/upload-artifact@v3
        working-directory: ./h3cuda_pkg
        with:
          name: h3cuda-wheel
          path: h3cuda_pkg/dist/*.whl
          if-no-files-found: error
